all_loc_ids = [
                # 'AT01',
                'AT02',
                'AT03',
                'AT04',
                'AT05',
                'AT06',
                'AT07',
                'AT08',
                'AT09',
                'AT10',
                'AT11',
                'BG02',
                'BG03',
                'BG04',
                'BG05',
                'BG06',
                'BG07',
                'BG08',
                'BG09',
                'BG10',
                'BG11',
                'BG12',
                'BG13',
                'BG14',
                'BG15',
                'BG16',
                'BG17',
                'BG18',
                'BG19',
                'BG20',
                'BG21',
                'BG22',
                'BG23',
                'BG24',
                'BG25',
                'BG28',
                'BG29',
                'BG30',
                'BG31',
                'BG32',
                'BG33',
                'BG34',
                'BG35',
                'BG36',
                "BG37",
                "BG38",
                "BG39",
                "BG40",
                'BG50',
                'BG51',
                'BG52',
                "P23",
                "SI01",
                "SI02",
                "SI03",
                "SI04",
                "SI06",
                "SI10",
                "SI11",
                "SI13",
                "SI14",
                "SI15",
                "SI16",
                "SI50",
                "SI51"]

all_plot_types = [
        'check data presence',
        'plot bed sensor data',
        'plot clip sensor data',
        'plot cooking',
        'plot walking'
        ]
DATA_COLLECTIONS = [
"SensorDataPackages-2020-12",
"SensorDataPackages-2021-1",
"SensorDataPackages-2021-2",
"SensorDataPackages-2021-3",
"SensorDataPackages-2021-4",
"SensorDataPackages-2021-5",
"SensorDataPackages-2021-6",
"SensorDataPackages"
]